// app/PublicLayout.tsx (ou o nome do seu layout)
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import "../globals.css";
import clsx from "clsx";

export const metadata: Metadata = {
  title: "Page Sign In",
  description: "Generated by create next app",
};

export default function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
      <div
        className={clsx("w-full h-full flex justify-center items-center p-2")}
      >
        {children}
      </div>
    </ThemeProvider>
  );
}
